#!/bin/bash

# link.sh - Create .cursorrules file from .ai-squads agents (Modern approach)
# Usage: ./link.sh [target_repo_path]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [target_repo_path]"
    echo ""
    echo "This script will create a modern .cursorrules file from .ai-squads agents."
    echo "This is the CURRENT recommended approach for Cursor configuration."
    echo ""
    echo "Arguments:"
    echo "  target_repo_path    Path to the target repository where .cursorrules will be created"
    echo "                      (optional - if not provided, uses current directory)"
    echo ""
    echo "Examples:"
    echo "  $0                    # Create .cursorrules in current directory"
    echo "  $0 ../my-project      # Create .cursorrules in specific repository"
    echo "  $0 /path/to/another/repo"
    echo ""
    echo "The script will:"
    echo "  1. Find the ai-squads repository"
    echo "  2. Scan all agents (.mdc), squads (.md), and workflows (.mdc)"
    echo "  3. Create a modern .cursorrules file with @agent: references"
    echo "  4. Use direct file paths (no symlinks needed)"
    echo ""
    echo "Modern approach benefits:"
    echo "  - No symlinks required"
    echo "  - Cleaner configuration"
    echo "  - Direct file references"
    echo "  - Better Cursor integration"
}

# Check if help is requested
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_usage
    exit 0
fi

# Check if target repository path is provided
if [ $# -eq 0 ]; then
    # No target provided, assume we want to link to current directory
    TARGET_REPO="."
    print_status "No target repository specified, using current directory"
else
    TARGET_REPO="$1"
fi

SOURCE_DIR=".ai-squads"

# Find ai-squads directory (local or external)
CURRENT_DIR=$(pwd)
LOCAL_AI_SQUADS="$CURRENT_DIR/$SOURCE_DIR"
EXTERNAL_AI_SQUADS="/Users/seb/projects/ai-squads/$SOURCE_DIR"

if [ -d "$LOCAL_AI_SQUADS" ]; then
    SOURCE_ABSOLUTE_PATH="$LOCAL_AI_SQUADS"
    print_status "Using local ai-squads at: $LOCAL_AI_SQUADS"
elif [ -d "$EXTERNAL_AI_SQUADS" ]; then
    SOURCE_ABSOLUTE_PATH="$EXTERNAL_AI_SQUADS"
    print_status "Using external ai-squads at: $EXTERNAL_AI_SQUADS"
else
    print_error "Could not find ai-squads directory"
    print_error "Please ensure .ai-squads exists in current directory or at /Users/seb/projects/ai-squads/"
    exit 1
fi

print_status "Starting creation of modern .cursorrules file"
print_status "Source directory: $SOURCE_ABSOLUTE_PATH"
print_status "Target repository: $TARGET_REPO"

# Check if source directory exists
if [ ! -d "$SOURCE_ABSOLUTE_PATH" ]; then
    print_error "Source directory '$SOURCE_ABSOLUTE_PATH' not found"
    print_error "Make sure the ai-squads repository exists at the expected location"
    exit 1
fi

# Check if target repository exists
if [ ! -d "$TARGET_REPO" ]; then
    print_error "Target repository '$TARGET_REPO' does not exist"
    exit 1
fi

# Create .cursorrules file
CURSORRULES_FILE="$TARGET_REPO/.cursorrules"
print_status "Creating modern .cursorrules file: $CURSORRULES_FILE"

# Start building the .cursorrules content
cat > "$CURSORRULES_FILE" << 'EOF'
# Cursor Rules for AI Squads Project
# Modern .cursorrules approach - direct file references
# Generated by link.sh

EOF

# Function to add agents from a directory (.mdc files)
add_agents_from_dir() {
    local dir_path="$1"
    local category="$2"
    
    if [ -d "$dir_path" ]; then
        echo "" >> "$CURSORRULES_FILE"
        echo "# $category" >> "$CURSORRULES_FILE"
        
        for file in "$dir_path"/*.mdc; do
            if [ -f "$file" ]; then
                filename=$(basename "$file")
                agent_name="${filename%.mdc}"
                echo "@agent:$agent_name $file" >> "$CURSORRULES_FILE"
                print_status "  ➕ Added agent: $agent_name"
            fi
        done
    fi
}

# Function to add squads from a directory (.md files)
add_squads_from_dir() {
    local dir_path="$1"
    local category="$2"
    
    if [ -d "$dir_path" ]; then
        echo "" >> "$CURSORRULES_FILE"
        echo "# $category" >> "$CURSORRULES_FILE"
        
        for file in "$dir_path"/*.md; do
            if [ -f "$file" ]; then
                filename=$(basename "$file")
                squad_name="${filename%.md}"
                echo "@agent:$squad_name $file" >> "$CURSORRULES_FILE"
                print_status "  ➕ Added squad: $squad_name"
            fi
        done
    fi
}

# Function to add workflows from a directory (.mdc files)
add_workflows_from_dir() {
    local dir_path="$1"
    local category="$2"
    
    if [ -d "$dir_path" ]; then
        echo "" >> "$CURSORRULES_FILE"
        echo "# $category" >> "$CURSORRULES_FILE"
        
        for file in "$dir_path"/*.mdc; do
            if [ -f "$file" ]; then
                filename=$(basename "$file")
                workflow_name="${filename%.mdc}"
                echo "@agent:$workflow_name $file" >> "$CURSORRULES_FILE"
                print_status "  ➕ Added workflow: $workflow_name"
            fi
        done
    fi
}

# Add agents (.mdc files)
print_status "Processing agents..."
add_agents_from_dir "$SOURCE_ABSOLUTE_PATH/agents" "Core Agents"

# Add squads (.md files)
print_status "Processing squads..."
add_squads_from_dir "$SOURCE_ABSOLUTE_PATH/squads" "Squads"

# Add workflows (.mdc files)
print_status "Processing workflows..."
add_workflows_from_dir "$SOURCE_ABSOLUTE_PATH/workflows" "Workflows"

# Add README if it exists (.md file)
if [ -f "$SOURCE_ABSOLUTE_PATH/workflows/README.md" ]; then
    echo "" >> "$CURSORRULES_FILE"
    echo "# Documentation" >> "$CURSORRULES_FILE"
    echo "@agent:readme $SOURCE_ABSOLUTE_PATH/workflows/README.md" >> "$CURSORRULES_FILE"
    print_status "  ➕ Added documentation: readme"
fi

print_success "Modern .cursorrules file created successfully!"
print_status "File location: $CURSORRULES_FILE"

# Show summary
print_status "Summary of created .cursorrules file:"
echo ""
cat "$CURSORRULES_FILE"
echo ""

print_success "✅ Modern Cursor configuration complete!"
print_status "This approach uses direct file references instead of symlinks"
print_status "Cursor will now use the .cursorrules file for agent configuration"
print_status "No .cursor/rules/ directory needed - this is the current best practice!"
